language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install -e .
  - pip install $DJANGO
  - pip install -r requirements-travisci.txt
script:
  - python test_project/runtests.py
env:
  - DJANGO="Django==1.4.20"
  - DJANGO="Django==1.5.12"
  - DJANGO="Django==1.6.11"
  - DJANGO="Django==1.7.8"
  - DJANGO="Django==1.8.2"

matrix:
  exclude:
    # Django 1.4 doesn't support Python 3
    - python: "3.3"
      env: DJANGO="Django==1.4.20"
    # Django 1.4 doesn't support Python 3
    - python: "3.4"
      env: DJANGO="Django==1.4.20"
