language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install -e .
  - pip install $DJANGO
  - pip install -r requirements-travisci.txt
  - pip install coveralls
script:
  - coverage run --source=test_plus setup.py test
after_success:
  - coveralls
env:
  - DJANGO="Django==1.6.11"
  - DJANGO="Django==1.7.8"
  - DJANGO="Django==1.8.2"
